# Generated by Django 4.1.6 on 2023-02-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfirstname', models.CharField(max_length=50)),
                ('blastname', models.CharField(max_length=10)),
                ('bemail', models.EmailField(max_length=30)),
                ('bnit', models.CharField(max_length=15)),
                ('bfile', models.BooleanField(default=False)),
                ('bfile2', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Estudiantes',
            },
        ),
    ]
