# Generated by Django 4.1.6 on 2023-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0002_proveedores_id_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='fecha_s',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
